dist: xenial
language: python

cache: pip

python:
- "3.7"
- "3.8"

matrix:
  allow_failures:
  - python: "3.8"

install:
- pip install -U -r requirements.txt

script:
- scripts/test

after_script:
- pip install codecov
- codecov
