site_name: Starlette Core
site_description: Starlette Core Documentation.

theme:
    name: 'material'

repo_name: accent-starlette/starlette-core
repo_url: https://github.com/accent-starlette/starlette-core
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Database: 'database.md'
    - Middleware: 'middleware.md'
    - Templating: 'templating.md'
    - Messages: 'messages.md'
    - Pagination: 'pagination.md'
    - Email: 'email.md'
    - Configuration: 'configuration.md'
    - Testing: 'testing.md'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
