site_name: Starlette Core
site_description: Starlette Core Documentation.

theme:
    name: 'material'

repo_name: accent-starlette/starlette-core
repo_url: https://github.com/accent-starlette/starlette-core
edit_uri: ""

nav:
    - Introduction: 'index.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
