#!/bin/sh -e

set -x

mypy starlette_core --ignore-missing-imports
autoflake --in-place --recursive --remove-unused-variables starlette_core tests
black starlette_core tests
isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --apply starlette_core tests
