#!/bin/sh -e

set -x

pytest --cov=starlette_core --cov-report=xml
mypy starlette_core --ignore-missing-imports
autoflake --recursive --remove-unused-variables starlette_core tests
black starlette_core tests --check
